### PR TITLE
Pine64 hacks

### PR DESCRIPTION
**Pull request by umiddelb**
Hi @longsleep 

these patches will enable basic docker support for the PINE64.

Cheers Uli

### CODE REVIEW

**Comment by longsleep** [comment]
Cool thanks. Some of the changes seem to have changed whitespace. Can you please check for the reason (eg. the defconfig file has completely changed).

**Comment by umiddelb** [comment]
I've used 

`make savedefconfig`

to compress the kernel configuration, see `make help` for details

**Comment by longsleep** [comment]
Ok i see, any particular reason? I think the format with the header sections help when developing and i would prefer to keep it that way for now if it is not too much of a problem.

**Comment by umiddelb** [comment]
`make sun50iw1p1smp_linux_defconfig` will give you the same .config back, but its easier to track changes or to migrate from one kernel version to another with 'compressed' defconfigs.

**Comment by umiddelb** [comment]
network performance is still poor, I've included support for USB ethernet adapters as well

**Comment by longsleep** [comment]
Ok makes sense :+1:

**Pull request merged**
